words = ( "Black", "Page 3", "Parineeta", "Iqbal", "Sarkar", "Omkara", "Rang De Basanti", "Lage Raho Munna Bhai", "Guru", "Chak De! India",
    "Jab We Met", "Taare Zameen Par", "A Wednesday!", "Rock On!!", "Ghajini", "Dev D", "Wake Up Sid", "3 Idiots", "Love Aaj Kal",
    "Kaminey", "Rocket Singh: Salesman of the Year", "Udaan", "Band Baaja Baaraat", "Peepli Live", "My Name is Khan", "Raajneeti",
    "Once Upon a Time in Mumbaai", "Dabangg", "Zindagi Na Milegi Dobara", "The Dirty Picture", "Rockstar", "Paan Singh Tomar",
    "Barfi!", "Kahaani", "Gangs of Wasseypur", "Vicky Donor", "English Vinglish", "Talaash", "Kai Po Che!", "Special 26",
    "Bhaag Milkha Bhaag", "Lootera", "Madras Cafe", "Shahid", "Raanjhanaa", "Chennai Express", "Queen", "Haider", "Highway",
    "PK", "Piku", "Masaan", "Tanu Weds Manu Returns", "Bajrangi Bhaijaan", "Tamasha", "Airlift", "Neerja", "Kapoor & Sons",
    "Udta Punjab", "Pink", "Dangal", "Dear Zindagi", "Raees", "Hindi Medium", "Toilet: Ek Prem Katha", "Newton", "Secret Superstar",
    "Tumhari Sulu", "Bareilly Ki Barfi", "Shubh Mangal Saavdhan", "Pad Man", "Raazi", "Andhadhun", "Stree", "Badhaai Ho",
    "Tumbbad", "URI: The Surgical Strike", "Gully Boy", "Article 15", "Chhichhore", "Bala", "Good Newwz", "Thappad", "Panga",
    "Shubh Mangal Zyada Saavdhan", "Ludo", "Serious Men", "Gunjan Saxena", "Sherni", "Shershaah", "Sardar Udham", "83", "The White Tiger",
    "Gangubai Kathiawadi", "Jersey", "Bhool Bhulaiyaa 2", "Jugjugg Jeeyo", "Laal Singh Chaddha", "Brahmastra", "Drishyam 2", "Qala",
    "Pathaan", "Tu Jhoothi Main Makkaar", "Mrs Chatterjee vs Norway", "Zara Hatke Zara Bachke", "Rocky Aur Rani Kii Prem Kahaani",
    "Jawan", "The Kerala Story", "OMG 2", "Gadar 2", "Animal", "Dunki", "Sam Bahadur", "12th Fail", "Laapataa Ladies", "Crew",
    "Bhakshak", "Teri Baaton Mein Aisa Uljha Jiya", "Yodha", "Madgaon Express", "Ae Watan Mere Watan", "Bade Miyan Chote Miyan",
    "Maidaan", "Srikanth", "Mr. and Mrs. Mahi", "Satyaprem Ki Katha", "Bheed", "The Archies", "Kho Gaye Hum Kahan", "Fighter",
    "Metro In Dino", "Merry Christmas", "Amar Singh Chamkila", "Chandu Champion", "Kill", "The Sabarmati Report", "Sarfira", "Bhool Bhulaiyaa 3",
    "Don 3", "Stree 2", "War 2", "Jigra", "Ulajh", "The Diplomat", "Vicky Vidya Ka Woh Wala Video", "Sky Force", "Baby John",
    "Housefull 5", "Welcome to the Jungle", "Singhan Again", "Baaghi 4", "Bhediya 2", "Yoddha", "Ghamasaan", "Nora", "Dukaan",
    "Afwaah", "Tejas", "Tiku Weds Sheru", "Babloo Bachelor", "Love Hostel", "India Lockdown", "Uunchai", "Runway 34", "Hit: The First Case",
    "Dasvi", "Jogi", "Babli Bouncer", "Kathal", "Mili", "Doctor G", "Double XL", "Phone Bhoot", "An Action Hero", "Gaslight",
    "Selfiee", "Shehzada", "Bholaa", "Kuttey", "Cirkus", "Liger", "Ek Villain Returns", "Freddy", "Govinda Naam Mera", "Darlings")

movie_hint_dict = {
    
    "Black": "Amitabh Bachchan, Rani Mukerji — 2005",
    "Page 3": "Konkona Sen Sharma — 2005",
    "Parineeta": "Vidya Balan, Saif Ali Khan — 2005",
    "Iqbal": "Shreyas Talpade — 2005",
    "Sarkar": "Amitabh Bachchan, Abhishek Bachchan — 2005",
    "Omkara": "Ajay Devgn, Saif Ali Khan — 2006",
    "Rang De Basanti": "Aamir Khan — 2006",
    "Lage Raho Munna Bhai": "Sanjay Dutt — 2006",
    "Guru": "Abhishek Bachchan, Aishwarya Rai — 2007",
    "Chak De! India": "Shah Rukh Khan — 2007",
    "Jab We Met": "Shahid Kapoor, Kareena Kapoor — 2007",
    "Taare Zameen Par": "Darsheel Safary, Aamir Khan — 2007",
    "A Wednesday!": "Naseeruddin Shah, Anupam Kher — 2008",
    "Rock On!!": "Farhan Akhtar — 2008",
    "Ghajini": "Aamir Khan — 2008",
    "Dev D": "Abhay Deol — 2009",
    "Wake Up Sid": "Ranbir Kapoor — 2009",
    "3 Idiots": "Aamir Khan — 2009",
    "Love Aaj Kal": "Saif Ali Khan, Deepika Padukone — 2009",
    "Kaminey": "Shahid Kapoor, Priyanka Chopra — 2009",
    "Rocket Singh: Salesman of the Year": "Ranbir Kapoor — 2009",
    "Udaan": "Rajat Barmecha — 2010",
    "Band Baaja Baaraat": "Ranveer Singh, Anushka Sharma — 2010",
    "Peepli Live": "Omkar Das Manikpuri — 2010",
    "My Name is Khan": "Shah Rukh Khan, Kajol — 2010",
    "Raajneeti": "Ranbir Kapoor, Katrina Kaif — 2010",
    "Once Upon a Time in Mumbaai": "Ajay Devgn, Emraan Hashmi — 2010",
    "Dabangg": "Salman Khan, Sonakshi Sinha — 2010",
    "Zindagi Na Milegi Dobara": "Hrithik Roshan, Farhan Akhtar — 2011",
    "The Dirty Picture": "Vidya Balan — 2011",
    "Rockstar": "Ranbir Kapoor — 2011",
    "Paan Singh Tomar": "Irrfan Khan — 2012",
    "Barfi!": "Ranbir Kapoor, Priyanka Chopra — 2012",
    "Kahaani": "Vidya Balan — 2012",
    "Gangs of Wasseypur": "Manoj Bajpayee, Nawazuddin Siddiqui — 2012",
    "Vicky Donor": "Ayushmann Khurrana — 2012",
    "English Vinglish": "Sridevi — 2012",
    "Talaash": "Aamir Khan, Rani Mukerji — 2012",
    "Kai Po Che!": "Sushant Singh Rajput — 2013",
    "Special 26": "Akshay Kumar — 2013",
    "Bhaag Milkha Bhaag": "Farhan Akhtar — 2013",
    "Lootera": "Ranveer Singh, Sonakshi Sinha — 2013",
    "Madras Cafe": "John Abraham — 2013",
    "Shahid": "Rajkummar Rao — 2013",
    "Raanjhanaa": "Dhanush, Sonam Kapoor — 2013",
    "Chennai Express": "Shah Rukh Khan, Deepika Padukone — 2013",
    "Queen": "Kangana Ranaut — 2014",
    "Haider": "Shahid Kapoor, Tabu — 2014",
    "Highway": "Alia Bhatt, Randeep Hooda — 2014",
    "PK": "Aamir Khan, Anushka Sharma — 2014",
    "Piku": "Amitabh Bachchan, Deepika Padukone — 2015",
    "Masaan": "Vicky Kaushal, Richa Chadha — 2015",
    "Tanu Weds Manu Returns": "Kangana Ranaut, R. Madhavan — 2015",
    "Bajrangi Bhaijaan": "Salman Khan, Harshaali Malhotra — 2015",
    "Tamasha": "Ranbir Kapoor, Deepika Padukone — 2015",
    "Airlift": "Akshay Kumar, Nimrat Kaur — 2016",
    "Neerja": "Sonam Kapoor, Shabana Azmi — 2016",
    "Kapoor & Sons": "Fawad Khan, Alia Bhatt — 2016",
    "Udta Punjab": "Shahid Kapoor, Alia Bhatt — 2016",
    "Pink": "Amitabh Bachchan, Taapsee Pannu — 2016",
    "Dangal": "Aamir Khan, Fatima Sana Shaikh — 2016",
    "Dear Zindagi": "Alia Bhatt, Shah Rukh Khan — 2016",
    "Raees": "Shah Rukh Khan, Mahira Khan — 2017",
    "Hindi Medium": "Irrfan Khan, Saba Qamar — 2017",
    "Toilet: Ek Prem Katha": "Akshay Kumar, Bhumi Pednekar — 2017",
    "Newton": "Rajkummar Rao, Pankaj Tripathi — 2017",
    "Secret Superstar": "Zaira Wasim, Aamir Khan — 2017",
    "Tumhari Sulu": "Vidya Balan — 2017",
    "Bareilly Ki Barfi": "Ayushmann Khurrana, Kriti Sanon — 2017",
    "Shubh Mangal Saavdhan": "Ayushmann Khurrana, Bhumi Pednekar — 2017",
    "Pad Man": "Akshay Kumar, Radhika Apte — 2018",
    "Raazi": "Alia Bhatt, Vicky Kaushal — 2018",
    "Andhadhun": "Ayushmann Khurrana, Tabu — 2018",
    "Stree": "Rajkummar Rao, Shraddha Kapoor — 2018",
    "Badhaai Ho": "Ayushmann Khurrana, Neena Gupta — 2018",
    "Tumbbad": "Sohum Shah — 2018",
    "URI: The Surgical Strike": "Vicky Kaushal, Yami Gautam — 2019",
    "Gully Boy": "Ranveer Singh, Alia Bhatt — 2019",
    "Article 15": "Ayushmann Khurrana — 2019",
    "Chhichhore": "Sushant Singh Rajput, Shraddha Kapoor — 2019",
    "Bala": "Ayushmann Khurrana, Yami Gautam — 2019",
    "Good Newwz": "Akshay Kumar, Kareena Kapoor — 2019",
    "Thappad": "Taapsee Pannu — 2020",
    "Panga": "Kangana Ranaut, Jassie Gill — 2020",
    "Shubh Mangal Zyada Saavdhan": "Ayushmann Khurrana, Jitendra Kumar — 2020",
    "Ludo": "Abhishek Bachchan, Rajkummar Rao — 2020",
    "Serious Men": "Nawazuddin Siddiqui — 2020",
    "Gunjan Saxena": "Janhvi Kapoor, Pankaj Tripathi — 2020",
    "Sherni": "Vidya Balan — 2021",
    "Shershaah": "Sidharth Malhotra, Kiara Advani — 2021",
    "Sardar Udham": "Vicky Kaushal — 2021",
    "83": "Ranveer Singh, Deepika Padukone — 2021",
    "The White Tiger": "Adarsh Gourav, Priyanka Chopra — 2021",
    "Gangubai Kathiawadi": "Alia Bhatt — 2022",
    "Jersey": "Shahid Kapoor — 2022",
    "Bhool Bhulaiyaa 2": "Kartik Aaryan, Kiara Advani — 2022",
    "Jugjugg Jeeyo": "Varun Dhawan, Kiara Advani — 2022",
    "Laal Singh Chaddha": "Aamir Khan, Kareena Kapoor — 2022",
    "Brahmastra": "Ranbir Kapoor, Alia Bhatt — 2022",
    "Drishyam 2": "Ajay Devgn, Tabu — 2022",
    "Qala": "Triptii Dimri, Babil Khan — 2022",
    "Pathaan": "Shah Rukh Khan, Deepika Padukone — 2023",
    "Tu Jhoothi Main Makkaar": "Ranbir Kapoor, Shraddha Kapoor — 2023",
    "Mrs Chatterjee vs Norway": "Rani Mukerji, Neena Gupta — 2023",
    "Zara Hatke Zara Bachke": "Vicky Kaushal, Sara Ali Khan — 2023",
    "Rocky Aur Rani Kii Prem Kahaani": "Ranveer Singh, Alia Bhatt — 2023",
    "Jawan": "Shah Rukh Khan, Nayanthara — 2023",
    "The Kerala Story": "Adah Sharma — 2023",
    "OMG 2": "Akshay Kumar, Pankaj Tripathi — 2023",
    "Gadar 2": "Sunny Deol, Ameesha Patel — 2023",
    "Animal": "Ranbir Kapoor, Rashmika Mandanna — 2023",
    "Dunki": "Shah Rukh Khan, Taapsee Pannu — 2023",
    "Sam Bahadur": "Vicky Kaushal, Fatima Sana Shaikh — 2023",
    "12th Fail": "Vikrant Massey, Medha Shankar — 2023",
    "Laapataa Ladies": "Nitanshi Goel, Pratibha Ranta — 2024",
    "Crew": "Kareena Kapoor, Tabu — 2024",
    "Bhakshak": "Bhumi Pednekar — 2024",
    "Metro In Dino": "Randeep Hooda, Shraddha Kapoor — 2024",
    "Merry Christmas": "Katrina Kaif, Vijay Sethupathi — 2024",
    "Fighter": "Hrithik Roshan, Deepika Padukone — 2024",
    "Amar Singh Chamkila": "Diljit Dosanjh — 2024",
    "Madgaon Express": "Priyanka Chahar Choudhary — 2024",
    "Housefull 5": "Akshay Kumar, Riteish Deshmukh — 2024",
    "Welcome to the Jungle": "Akshay Kumar, Kareena Kapoor — 2024",
    "Singhan Again": "Tiger Shroff — 2024",
    "Baaghi 4": "Shraddha Kapoor — 2024",
    "Bhediya 2": "Varun Dhawan — 2024",
    "Yoddha": "Sidharth Malhotra — 2024",
    "Ghamasaan": "Aditi Rao Hydari — 2024",
    "Nora": "Janhvi Kapoor — 2024",
    "Dukaan": "Arjun Kapoor — 2024",
    "Afwaah": "Taapsee Pannu — 2024",
    "Tejas": "Kriti Sanon — 2024",
    "Tiku Weds Sheru": "Kartik Aaryan — 2024",
    "Babloo Bachelor": "Sunny Kaushal — 2024",
    "Love Hostel": "Vijay Varma — 2024",
    "India Lockdown": "Ananya Panday — 2024",
    "Uunchai": "Amitabh Bachchan, Boman Irani — 2022",
    "Runway 34": "Ajay Devgn, Rakul Preet Singh — 2022",
    "Hit: The First Case": "Rajkummar Rao, Sanya Malhotra — 2022",
    "Dasvi": "Abhimanyu Singh — 2022",
    "Jogi": "Dilip Joshi — 2022",
    "Babli Bouncer": "Kartik Aaryan — 2022",
    "Kathal": "Sharvari Wagh — 2023",
    "Mili": "Janvi Kapoor — 2022",
    "Doctor G": "Ayushmann Khurrana — 2022",
    "Double XL": "Sonakshi Sinha — 2022",
    "Phone Bhoot": "Siddhant Chaturvedi, Katrina Kaif — 2022",
    "An Action Hero": "Ayushmann Khurrana — 2022",
    "Gaslight": "Sara Ali Khan — 2022",
    "Selfiee": "Akshay Kumar, Emraan Hashmi — 2023",
    "Shehzada": "Kartik Aaryan — 2023",
    "Bholaa": "Ajay Devgn — 2023",
    "Kuttey": "Tabu, Arjun Kapoor — 2023",
    "Cirkus": "Ranveer Singh — 2022",
    "Liger": "Vijay Deverakonda — 2022",
    "Ek Villain Returns": "John Abraham, Tara Sutaria — 2022",
    "Govinda Naam Mera": "Vicky Kaushal — 2022",
    "Darlings": "Alia Bhatt — 2022"
}



